Fix error caused by a blockquote inside a p tag on About page
codeforgso/codeforgso.github.io pull request #29
Opened 2019-10-05 21:02 UTC by ggangix

## Description
There was an error on the About page caused by a blockquote tag inside a p tag, so I have replaced the p tag with a div with the same style as a paragraph.

## Related Issue

#23 

## Motivation and Context

Fix the error on the about page.

## How Has This Been Tested?

I just tested on the browser.

## Screenshots (if appropriate):

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-10-06 15:36 UTC, braidn commented
Thanks for looking into this @ggangix , will look at it in a bit and get this merged.

2019-10-07 13:38 UTC, SchaeStewart requested changes
Thank you so much for contributing! I've left a few comments and I'm asking that you make a few changes before I merge your PR. Let me know if you have any questions

2019-10-07 13:38 UTC, SchaeStewart commented on styles.scss
> +
Remove this.

2019-10-07 13:38 UTC, SchaeStewart commented on pages/about.js
> +        </div>
Instead of creating a new class and using a div, try just moving the `blockquote` outside of the `p` tag

2019-10-07 18:27 UTC, ggangix commented
Thanks for the feedback, the solution was more simple :)

2019-10-07 21:35 UTC, merged

2019-10-07 21:35 UTC, SchaeStewart commented
Thanks!